### ISSUE TITLE
Changes in the GitHub Actions?

### ISSUE THREAD

**Issue by dubinsky** [github-actions-x/commit#16]
Something changed in GitHub Actions recently (for instance, there is now "Post Check out the code" 
step in my build log); v2.2 started crashing with some Python stacktrace; v2.6 does not crash,
but no changes get pushed (I just get "Your branch is up to date"). When I added `rebase: true`, I got: "Please tell me who you are. ... user.email ... user.name ..." - looks like defaults do not apply in the `rebase` case, so I had to set email and name explicitly...

**Comment by paskal** [comment]
I see similar picture. Code:

```
    - name: git status
      run: git status
    - name: commit kernel-specific library
      uses: github-actions-x/commit@v2.6
      with:
        github-token: ${{ secrets.BPFINK_COMMIT_TOKEN }}
        commit-message: 'bump kernel-specific libraries'
```

[Output](https://github.com/bookingcom/bpfink/runs/784218814?check_suite_focus=true#step:10:9):

```
---
Run git status
On branch automated_build
Your branch is up to date with 'origin/automated_build'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   pkg/ebpf/vfs-3.10.o

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	golangci-lint
	profile.cov

no changes added to commit (use "git add" and/or "git commit -a")

---
Run github-actions-x/commit@v2.6
login paskal
password ***
machine api.github.com
login paskal
password ***

Your branch is up to date with 'origin/automated_build'.
```
