### ISSUE TITLE
Git login is None，commit user is None.

### ISSUE THREAD

**Issue by lework** [github-actions-x/commit#3]
usage:
```yaml
- name: Push
      uses: github-actions-x/commit@v2.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        push-branch: 'master'
        commit-message: 'This is an github action commit.'
        force-add: 'true'
```

``` bash
/usr/bin/docker run --name df7dcc5243786e4a94c62a0fff92ae4f161ea_ad780e --label 0df7dc --workdir /github/workspace --rm -e pythonLocation -e INPUT_GITHUB-TOKEN -e INPUT_PUSH-BRANCH -e INPUT_COMMIT-MESSAGE -e INPUT_FORCE-ADD -e HOME -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/leversion/leversion":"/github/workspace" 0df7dc:c5243786e4a94c62a0fff92ae4f161ea
 login None
password ***
machine api.github.com
login None
password ***
```
