### ISSUE TITLE
feature: add ability to specify path

### ISSUE THREAD

**Issue by moltar** [github-actions-x/commit#6]
Would be great to be able to specify a path to add. E.g. I want to generate some test recordings and only add them, and ignore any other changes.

Something like:

```yaml
    - name: push
      uses: github-actions-x/commit@v2.1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'test: adds Polly recordings'
        files: tests/
```

Thanks!
